spring:
  application:
    name: coroutine.webflux
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/webflux_kotlin_mongo
      database: webflux_kotlin_mongo
      username: root
      password: password